### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by davesnx** [raine/ramda-json-docs-generator#1]
I'm trying to run `./ramda-src-to-json.ls` and I got an error. Using node v10.

```
./ramda-src-to-json.ls node_modules/ramda/dist/ramda.js
Failed at: ./ramda-src-to-json.ls
TypeError: Cannot read property 'length' of undefined
```

**Comment by raine** [comment]
Thanks. Overlooked that file when making fixes few months ago.

I use `fetch-github-tags.ls` for generating https://github.com/raine/ramda-json-docs

https://github.com/raine/ramda-json-docs/blob/gh-pages/etc/run.sh
